DEFINE INDEX embeddings_0_hnsw_idx ON TABLE embeddings_0 COLUMNS embedding HNSW DIMENSION 1024 TYPE F32 DIST COSINE M 4 EFC 32;
DEFINE INDEX embeddings_1_hnsw_idx ON TABLE embeddings_1 COLUMNS embedding HNSW DIMENSION 1024 TYPE F32 DIST COSINE M 4 EFC 32;
DEFINE INDEX embeddings_2_hnsw_idx ON TABLE embeddings_2 COLUMNS embedding HNSW DIMENSION 1024 TYPE F32 DIST COSINE M 4 EFC 32;
